### ISSUE TITLE
Respecto a la estructura del sitio visualizar que contenga estos elementos cada sección

### ISSUE THREAD

**Issue by lucianoalive90** [Cainenk011/ML.yamal.e.maldonado#1]
# _**Respecto a la estructura del sitio visualizar que contenga estos elementos cada sección**_

## Header:

> ●  Logo     **_CUMPLIDO_**
> ●   Barra de búsqueda     **_CUMPLIDO_**
> ●   Comprá en cuotas y sin tarjeta de crédito      **_CUMPLIDO_**
> ●   Barra de navegación:      **_CUMPLIDO_**
> ●   Ofertas     **_CUMPLIDO_**
> ●   Tiendas Oﬁciales     **_CUMPLIDO_**
> ●   Vender     **_CUMPLIDO_**
> ●   Ayuda     **_CUMPLIDO_**
> ●   Login     **_CUMPLIDO_**
> ●   Registro     **_CUMPLIDO_**
> ●   Mis compras     **_CUMPLIDO_**
> 

## Main:

> ●  Sección basada en las últimas visitas     **_CUMPLIDO_**
> ●  Sección de ofertas     **_CUMPLIDO_**

## Footer:

> ●  Pagá con tarjeta o en efectivo     **_CUMPLIDO_**
> ●  Envío gratis desde $ 2.500     **_CUMPLIDO_**
> ●  Seguridad, de principio a ﬁn     **_CUMPLIDO_**
> ●  Copyright © 1999-2022 MercadoLiebre S.R.L.     **_CUMPLIDO_**

**Comment by Cainenk011** [comment]
Gracias
